version: "3"
services:
  mirrors:
    restart: always
    image: zhouerqin/mirrors:0.1.0
    env_file:
      - mirrors.env
    build:
      context: mirrors
    volumes:
      - repos:/data/repos
    ports:
      - "80:80"

volumes:
  repos:
