version: "3"
services:
  mirror:
    restart: always
    image: zhouerqin/mirror:0.1.0
    env_file:
      - mirror.env
    build:
      context: mirror
    volumes:
      - repos:/data/repos
    ports:
      - "80:80"

volumes:
  repos:
