version: "3"
services:
  nginx:
    restart: always
    image: nginx:1.22
    volumes:
      - ./nginx:/etc/nginx
      - mirror-repos:/data/repos
    ports:
      - "80:80"

volumes:
  mirror-repos:
